### ISSUE TITLE
textCtrl size should change according to font size

### ISSUE THREAD

**Issue by sk-Prime** [khchen/wNim#34]
```Nim
let textentry = TextCtrl(panel, value="", style=wBorderSunken)
textentry.font = Font(20, faceName="consolas")
```
in this example, `textCtrl` can not show font properly because the font size is bigger than textCtrl size.

Q: how to change `textCtrl` size manualy, as `textentry.fit()` make `textCtrl` size smallest because init value is = "", and i don't want to change `textCtrl` length, i want it to be fixed length. if there are 4 char in `textCtrl`, the fit() make it small and show only 4 char.

**Comment by khchen** [comment]
1. You can change the font of the panel before `wTextCtrl` creation. Because the font is inheritable. So the `wTextCtrl` will get the correct size when creation.

2. If you change the font of a control after creation. You can set the size to its `getDefaultSize()`.  And this is what `wWindow.suit()` does. For example: `textentry.suit()` or `textentry.size = textentry.defaultSize`, it in actually is `textentry.setSize(textentry.getDefaultSize())`.

3. For current implementation, getDefaultSize() for wTextCtrl use a fix width. You can also change it after suit() but keep the height. For example: `textentry.size = (200, wDefault)`.

**Comment by sk-Prime** [comment]
thanks it solves the problem.
