### ISSUE TITLE
Nested StaticBox

### ISSUE THREAD

**Issue by f-carraro** [khchen/wNim#35]
Is this supported in wNim? I tried the following code:

```
import wNim

let app = App()
let frame = Frame(title="Hello World", size=(400, 300))

let panel = Panel(frame)
let st1 = StaticBox(panel,label="StaticBox 1")
let st2 = StaticBox(st1,label="StaticBox 2")

frame.autolayout """
   spacing:4
   HV:|-[st1]-|
   outer: st1 
   HV:|-[st2]-|
   """
frame.center()
frame.show()
app.mainLoop()
```

In the result the label of the second staticbox is different, and the spacing seems off.

**Comment by khchen** [comment]
What you want to do may like this:

```nim
let panel = Panel(frame)
let st1 = StaticBox(panel, label="StaticBox 1")
let st2 = StaticBox(st1, label="StaticBox 2")

panel.autolayout """
   spacing:4
   HV:|-[st1]-|
   """

st1.autolayout """
   spacing:4
   HV:|-[st2]-|
  """
```

The rule of layout/autolayout is: A parent changes layout for it's child (`parent.autolayout "|[child]|"`). Naturally, the default outer border (the `|` symbol in autolayout format language) is just the border of the parent.

However, above code works in logically, but may look ugly. Because wStaticBox should not be a "parent window" in Windows (In fact, wStaticBox is just a WC_BUTTON with BS_GROUPBOX style). All object inside wStaticBox should be it's sibling, not it's children. 

So the problem is: for what we want to put into a wStaticBox, the outer border symbol (`|`) should be aligned with a sibling, not parent! `outer` keyword help us to specify a sibling object to align with. This is why we often use `outer` keyword for wStaticBox layout (and maybe the only usage).

Finally, the correct code should be:
```nim
let panel = Panel(frame)
let st1 = StaticBox(panel, label="StaticBox 1")
let st2 = StaticBox(panel, label="StaticBox 2")

panel.autolayout """
 spacing: 4
 HV:|-[st2]-|

 outer: st2
 HV:|-[st1]-|
 """
```

I hope you can understand what I said. My English seems not good enough to explain it well. 
Ps. Similar demonstration code is in examples/layout3.nim.

**Comment by f-carraro** [comment]
Excelent response, I understand now. It was perfecly clear. Thank you for such a complete response and for creating this great framework!
